question_data = [
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "How many games in the Crash Bandicoot series were released on the original Playstation?",
     "correct_answer": "5", "incorrect_answers": ["4", "3", "6"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "What is not a wind instrument?", "correct_answer": "Viola",
     "incorrect_answers": ["Oboe", "Trombone", "Duduk"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "What genre of EDM is the Dutch DJ, musician, and remixer Armin van Buuren most well-known for?",
     "correct_answer": "Trance", "incorrect_answers": ["House", "Drum and Bass", "Dubstep"]},
    {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
     "question": "Automobiles produced by Telsa Motors operate on which form of energy?",
     "correct_answer": "Electricity", "incorrect_answers": ["Gasoline", "Diesel", "Nuclear"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of the main character in &quot;The Flash&quot; TV series?",
     "correct_answer": "Barry Allen", "incorrect_answers": ["Oliver Queen", "Bart Allen", "Bruce Wayne"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In which year did the first Monster Hunter game get released?", "correct_answer": "2004",
     "incorrect_answers": ["2006", "2005", "2002"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following Terran units from the RTS game "
                 "Starcraft was first introduced in the expansion Brood War?",
     "correct_answer": "Medic", "incorrect_answers": ["Wraith", "Science Vessel", "SCV"]},
    {"category": "Science: Gadgets", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following is used to measure blood pressure?", "correct_answer": "Sphygmomanometer",
     "incorrect_answers": ["Barometer", "Ruler", "Haemoerythrometer"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium", "question": "What is Hypernatremia?",
     "correct_answer": "Increase in blood sodium",
     "incorrect_answers": ["Decrease in blood potassium", "Increase in blood glucose", "Decrease in blood iron"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "In the Team Fortress 2 canon, what did Shakespearicles NOT invent?", "correct_answer": "Stairs",
     "incorrect_answers": ["Two-Story Building", "Rocket Launcher", "Stage Play"]}]
